# Generated by Django 4.0.5 on 2022-07-04 15:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anon',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
